//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP03ClientDonne
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tp03BDEntities1 : DbContext
    {
        public Tp03BDEntities1()
            : base("name=Tp03BDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aptitude> Aptitude { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Conference> Conference { get; set; }
        public virtual DbSet<MembreCO> MembreCO { get; set; }
        public virtual DbSet<MembreCP> MembreCP { get; set; }
        public virtual DbSet<MembreCP_Article> MembreCP_Article { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<Participant_Article> Participant_Article { get; set; }
    }
}
