//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP03ClientDonne
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tp03BDEntities : DbContext
    {
        public Tp03BDEntities()
            : base("name=Tp03BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aptitude> Aptitudes { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<MembreCO> MembreCOes { get; set; }
        public virtual DbSet<MembreCP> MembreCPs { get; set; }
        public virtual DbSet<MembreCP_Article> MembreCP_Article { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Participant_Article> Participant_Article { get; set; }
    }
}
