//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP03ClientDonne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant_Article
    {
        public int Id { get; set; }
        public Nullable<int> ParticipantId { get; set; }
        public int ArticleId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
