//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceClient1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IParticipantService")]
    public interface IParticipantService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipantService/InscrireParticipants", ReplyAction="http://tempuri.org/IParticipantService/InscrireParticipantsResponse")]
        int InscrireParticipants(string prenom, string nom, string email, string affiliation, System.DateTime DateInscription, decimal frais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipantService/InscrireParticipants", ReplyAction="http://tempuri.org/IParticipantService/InscrireParticipantsResponse")]
        System.Threading.Tasks.Task<int> InscrireParticipantsAsync(string prenom, string nom, string email, string affiliation, System.DateTime DateInscription, decimal frais);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParticipantServiceChannel : ConferenceClient1.ServiceReference1.IParticipantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParticipantServiceClient : System.ServiceModel.ClientBase<ConferenceClient1.ServiceReference1.IParticipantService>, ConferenceClient1.ServiceReference1.IParticipantService {
        
        public ParticipantServiceClient() {
        }
        
        public ParticipantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParticipantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParticipantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParticipantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InscrireParticipants(string prenom, string nom, string email, string affiliation, System.DateTime DateInscription, decimal frais) {
            return base.Channel.InscrireParticipants(prenom, nom, email, affiliation, DateInscription, frais);
        }
        
        public System.Threading.Tasks.Task<int> InscrireParticipantsAsync(string prenom, string nom, string email, string affiliation, System.DateTime DateInscription, decimal frais) {
            return base.Channel.InscrireParticipantsAsync(prenom, nom, email, affiliation, DateInscription, frais);
        }
    }
}
