//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembreCP
    {
        public MembreCP()
        {
            this.Aptitude = new HashSet<Aptitude>();
            this.Conference = new HashSet<Conference>();
            this.MembreCP_Article = new HashSet<MembreCP_Article>();
            this.Note = new HashSet<Note>();
        }
    
        public int Id { get; set; }
        public int ParticipantId { get; set; }
    
        public virtual ICollection<Aptitude> Aptitude { get; set; }
        public virtual ICollection<Conference> Conference { get; set; }
        public virtual ICollection<MembreCP_Article> MembreCP_Article { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual ICollection<Note> Note { get; set; }
    }
}
