//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_GUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tp03BDEntities : DbContext
    {
        public Tp03BDEntities()
            : base("name=Tp03BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aptitude> Aptitude { get; set; }
        public DbSet<Article> Article { get; set; }
        public DbSet<Conference> Conference { get; set; }
        public DbSet<MembreCO> MembreCO { get; set; }
        public DbSet<MembreCP> MembreCP { get; set; }
        public DbSet<MembreCP_Article> MembreCP_Article { get; set; }
        public DbSet<Note> Note { get; set; }
        public DbSet<Participant> Participant { get; set; }
        public DbSet<Participant_Article> Participant_Article { get; set; }
    }
}
